package org.example.coursework2026marina.common;

public enum Command {
    REGISTER,
    LOGIN,
    GET_USER_PROFILE,
    CHANGE_PASSWORD,
    GET_MY_PROGRESS,
    GET_AVAILABLE_PROGRAMS,
    ENROLL_PROGRAM,
    CREATE_PROGRAM,
    CREATE_MODULE,
    CREATE_ASSIGNMENT,
    RECORD_STUDENT_GRADE,
    GET_PROGRAM_ASSIGNMENTS,
    SUBMIT_ASSIGNMENT,
    GET_MY_SUBMISSIONS,
    GET_ASSIGNMENT_SUBMISSIONS,
    GET_ALL_ANALYTICS,
    GET_STUDENT_LIST,
    PING
}
